.PHONY: clean All

All:
	@echo "----------Building project:[ practica3 - Debug ]----------"
	@cd "practica3" && $(MAKE) -f  "practica3.mk"
clean:
	@echo "----------Cleaning project:[ practica3 - Debug ]----------"
	@cd "practica3" && $(MAKE) -f  "practica3.mk" clean
