.PHONY: clean All

All:
	@echo "----------Building project:[ Lychrel - Debug ]----------"
	@cd "Lychrel" && "$(MAKE)" -f  "Lychrel.mk"
clean:
	@echo "----------Cleaning project:[ Lychrel - Debug ]----------"
	@cd "Lychrel" && "$(MAKE)" -f  "Lychrel.mk" clean
