.PHONY: clean All

All:
	@echo "----------Building project:[ Trabajo - Debug ]----------"
	@cd "Trabajo" && "$(MAKE)" -f  "Trabajo.mk"
clean:
	@echo "----------Cleaning project:[ Trabajo - Debug ]----------"
	@cd "Trabajo" && "$(MAKE)" -f  "Trabajo.mk" clean
