.PHONY: clean All

All:
	@echo "----------Building project:[ Valorar - Debug ]----------"
	@cd "Valorar" && "$(MAKE)" -f  "Valorar.mk"
clean:
	@echo "----------Cleaning project:[ Valorar - Debug ]----------"
	@cd "Valorar" && "$(MAKE)" -f  "Valorar.mk" clean
