.PHONY: clean All

All:
	@echo "----------Building project:[ FechasTest - Debug ]----------"
	@cd "FechasTest" && "$(MAKE)" -f  "FechasTest.mk"
clean:
	@echo "----------Cleaning project:[ FechasTest - Debug ]----------"
	@cd "FechasTest" && "$(MAKE)" -f  "FechasTest.mk" clean
