.PHONY: clean All

All:
	@echo "----------Building project:[ Estaciones - Debug ]----------"
	@cd "Estaciones" && "$(MAKE)" -f  "Estaciones.mk"
clean:
	@echo "----------Cleaning project:[ Estaciones - Debug ]----------"
	@cd "Estaciones" && "$(MAKE)" -f  "Estaciones.mk" clean
